# Generated by Django 3.1.3 on 2023-06-01 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pybo', '0007_auto_20230602_0132'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='modified_count',
            field=models.IntegerField(default=0),
        ),
    ]
