# Generated by Django 4.2.1 on 2023-06-06 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pybo', '0007_answer_modify_cnt_question_modify_cnt'),
        ('pybo', '0008_comment_modified_count'),
    ]

    operations = [
    ]
